n1=float(input('Numero 1:'))
p1=float(input('Ponderacion 1:'))
n2=float(input('Numero 2:'))
p2=float(input('Ponderacion 2:'))
n3=float(input('Numero 3:'))
p3=float(input('Ponderacion 3:'))
media=((n1*p1)+(n2*p2)+(n3*p3))/(p1+p2+p3)
print('La media es de '+str(media))